language: ruby
rvm:
  - 2.1.0
  # - 2.0.0
  # - 1.9.3
gemfile:
  - Gemfile
branches:
  only:
    - master
env:
  - "REDMINE_LANG=en REDMINE_VERSION=2.5.1 DATABASE_ADAPTER=mysql"
  - "REDMINE_LANG=en REDMINE_VERSION=2.5.0 DATABASE_ADAPTER=mysql"
  - "REDMINE_LANG=en REDMINE_VERSION=2.4.5 DATABASE_ADAPTER=mysql"
  - "REDMINE_LANG=en REDMINE_VERSION=2.4.4 DATABASE_ADAPTER=mysql"
  - "REDMINE_LANG=en REDMINE_VERSION=2.4.3 DATABASE_ADAPTER=mysql"
  - "REDMINE_LANG=en REDMINE_VERSION=2.4.2 DATABASE_ADAPTER=mysql"
  - "REDMINE_LANG=en REDMINE_VERSION=2.4.1 DATABASE_ADAPTER=mysql"
  - "REDMINE_LANG=en REDMINE_VERSION=2.4.0 DATABASE_ADAPTER=mysql"
  - "REDMINE_LANG=en REDMINE_VERSION=2.3.4 DATABASE_ADAPTER=mysql"
  - "REDMINE_LANG=en REDMINE_VERSION=2.2.4 DATABASE_ADAPTER=mysql"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libicu-dev
  - cd ../..
  - ./n-rodriguez/redmine_diff_email/contrib/travis/install_redmine.sh
  - cd redmine
  - echo $(pwd)
  - export BUNDLE_GEMFILE=$PWD/Gemfile
before_script:
  - echo $(pwd)
  - mysql -e 'create database redmine;'
  - mysql -e 'create database redmine_test;'
  - psql -c 'create database redmine;' -U postgres
  - psql -c 'create database redmine_test;' -U postgres
  - bundle exec rake generate_secret_token
  - bundle exec rake db:migrate
  - bundle exec rake redmine:load_default_data
  - bundle exec rake redmine:plugins:migrate
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake redmine_diff_email:test
